from models.model_dependencies import MobileNetV2_trained as MobileNetV2
from models.model_dependencies import ConvNeXtTiny_trained as ConvNeXtTiny
from models.model_dependencies import ConvNeXtTiny_averaged_leftright_trained as ConvNeXtTiny_leftright
from models.model_dependencies import ConvNeXtTiny_averaged_updown_trained as ConvNeXtTiny_updown
from models.model_dependencies import ConvNeXtTiny_averaged_trained as ConvNeXtTiny_averaged
from models.model_dependencies import EfficientNetV2S_trained as EfficientNetV2S
from models.model_dependencies import EfficientNetV2S_averaged_leftright_trained as EfficientNetV2S_leftright
from models.model_dependencies import EfficientNetV2S_averaged_updown_trained as EfficientNetV2S_updown
from models.model_dependencies import EfficientNetV2S_averaged_trained as EfficientNetV2S_averaged
from models.model_dependencies import Ensemble_model_trained as Ensemble
from models.model_dependencies import Ensemble_model_averaged_trained as Ensemble_averaged


all_models =[MobileNetV2,ConvNeXtTiny,ConvNeXtTiny_leftright,ConvNeXtTiny_updown,ConvNeXtTiny_averaged,EfficientNetV2S,EfficientNetV2S_leftright,EfficientNetV2S_updown,EfficientNetV2S_averaged,Ensemble,Ensemble_averaged]
all_models_names=['MobileNetV2','ConvNeXtTiny','ConvNeXtTiny_leftright','ConvNeXtTiny_updown','ConvNeXtTiny_averaged','EfficientNetV2S','EfficientNetV2S_leftright','EfficientNetV2S_updown','EfficientNetV2S_averaged','Ensemble','Ensemble_averaged']